var local = {
                "user_account_login":{"url":"../data/user_account_login.json","version":"1.0"},//登录
                "project_type_list":{"url":"../data/project_type_list.json","version":"1.0"},//项目模板列表
                "project_type_add":{"url":"../data/project_type_add.json","version":"1.0"},//项目模板新增
                "project_manage_list":{"url":"../data/project_manage_list.json","version":"1.0"},//项目列表
                "project_manage_add":{"url":"../data/project_manage_add.json","version":"1.0"},//项目新增
                "project_data_edit":{"url":"../data/project_data_edit.json","version":"1.0"},//项目修改
                "project_data_getByProjectId":{"url":"../data/project_data_getByProjectId.json","version":"1.0"},//获取一条项目信息
                "staff_manage_list":{"url":"../data/staff_manage_list.json","version":"1.0"},//实施负责人
                "program_manage_list":{"url":"../data/program_manage_list.json","version":"1.0"},// 项目集列表
                "program_manage_add":{"url":"../data/program_manage_add.json","version":"1.0"},//项目集新增
                "program_data_getByProjectId":{"url":"../data/program_data_getByProjectId.json","version":"1.0"},
                "lecturer_manage_list":{"url":"../data/lecturer_manage_list.json","version":"1.0"},//讲师列表
                "lecturer_manage_add":{"url":"../data/lecturer_manage_add.json","version":"1.0"},//讲师新增
                "lecturer_duty_list":{"url":"../data/lecturer_duty_list.json","version":"1.0"},//讲师职责列表
                "lecturer_duty_add":{"url":"../data/lecturer_duty_add.json","version":"1.0"},//讲师职责新增
                "lecturer_plan_getByProjectId":{"url":"../data/lecturer_plan_getByProjectId.json","version":"1.0"},//获取项目讲师安排
                "lecturer_plan_add":{"url":"../data/lecturer_plan_add.json","version":"1.0"},//讲师安排新增
                "lecturer_plan_edit":{"url":"../data/lecturer_plan_edit.json","version":"1.0"},//讲师安排修改
                "lecturer_plan_del":{"url":"../data/lecturer_plan_del.json","version":"1.0"},//讲师安排删除
                "lecturer_manage_cooperation":{"url":"../data/lecturer_manage_cooperation.json","version":"1.0"},//讲师合作模式
                "implement_venue_add":{"url":"../data/implement_venue_add.json","version":"1.0"},//会场安排新增
                "implement_venue_edit":{"url":"../data/implement_venue_edit.json","version":"1.0"},//会场安排修改
                "implement_venue_del":{"url":"../data/implement_venue_del.json","version":"1.0"},//会场安排删除
                "implement_plan_getByProjectId":{"url":"../data/implement_plan_getByProjectId.json","version":"1.0"},//获取实施安排列表
                "implement_plan_edit":{"url":"../data/implement_plan_edit.json","version":"1.0"},//实施安排修改
                "travel_plan_getByProjectId":{"url":"../data/travel_plan_getByProjectId.json","version":"1.0"},//获取差旅安排
                "travel_inCityTraffic_add":{"url":"../data/travel_inCityTraffic_add.json","version":"1.0"},//市内新增
                "travel_inCityTraffic_edit":{"url":"../data/travel_inCityTraffic_edit.json","version":"1.0"},//市内修改
                "travel_inCityTraffic_del":{"url":"../data/travel_inCityTraffic_del.json","version":"1.0"},//市内删除
                "travel_longTraffic_add":{"url":"../data/travel_longTraffic_add.json","version":"1.0"},//长途新增
                "travel_longTraffic_edit":{"url":"../data/travel_longTraffic_edit.json","version":"1.0"},//长途修改
                "travel_longTraffic_del":{"url":"../data/travel_longTraffic_del.json","version":"1.0"},//长途删除
                "travel_longTrafficType_list":{"url":"../data/travel_longTrafficType_list.json","version":"1.0"},//长途类型列表
                "travel_hotel_add":{"url":"../data/travel_hotel_add.json","version":"1.0"},//住宿费新增
                "travel_hotel_edit":{"url":"../data/travel_hotel_edit.json","version":"1.0"},//住宿费修改
                "travel_hotel_del":{"url":"../data/travel_hotel_del.json","version":"1.0"},//住宿费删除
                "Project":{"url":"../data/Project.json","version":"1.0"},//发送数据列表
                "json_manage_list":{"url":"../data/json_manage_list.json","version":"1.0"},//视图管理表
                 "json_manage_name":{"url":"../data/json_manage_name.json","version":"1.0"},//通过名称找视图数据
                "view_type":{"url":"../data/view_type.json","version":"1.0"},//视图类型
                "view_mode":{"url":"../data/view_mode.json","version":"1.0"},//视图模块
                "new_view":{"url":"../data/new_view.json","version":"1.0"},//新增视图
                "menu_data_list":{"url":"../data/menu_data_list.json","version":"1.0"},//菜单角色list
                "menu_data_getone":{"url":"../data/menu_data_getone.json","version":"1.0"},
                "menu_manage_add":{"url":"../data/menu_manage_add.json","version":"1.0"},
                "menu_manage_edit":{"url":"../data/menu_manage_edit.json","version":"1.0"},
                "menu_manage_list":{"url":"../data/menu_manage_list.json","version":"1.0"},//菜单管理
                "examine_manage_commitbudget":{"url":"../data/examine_manage_commitbudget.json","version":"1.0"},//提交预算接口
                "examine_manage_commitfinal":{"url":"../data/examine_manage_commitfinal.json","version":"1.0"},//提交决算接口
                "examine_manage_bool":{"url":"../data/examine_manage_bool.json","version":"1.0"},//预算审批接口
                "examine_budget_list":{"url":"../data/examine_budget_list.json","version":"1.0"},//预算审批list
                "role_route_list":{"url":"../data/role_route_list.json","version":"1.0"},
                "get_route_by_role_id":{"url":"../data/get_route_by_role_id.json","version":"1.0"},
                "client_route_list":{"url":"../data/client_route_list.json","version":"1.0"},
                "examine_record_list":{"url":"../data/examine_record_list.json","version":"1.0"},
                "payment_manage_add":{"url":"../data/payment_manage_add.json","version":"1.0"},//创建支出
                "payment_manage_my_list":{"url":"../data/payment_manage_my_list.json","version":"1.0"},//查看我的支出
                "payment_manage_by":{"url":"../data/payment_manage_by.json","version":"1.0"},//查看我的支出
                "payment_manage_my_dep_list":{"url":"../data/payment_manage_my_dep_list.json","version":"1.0"},//查看部门支出
                "payment_manage_list":{"url":"../data/payment_manage_list.json","version":"1.0"},//查看所有支出
                "payment_manage_edit":{"url":"../data/payment_manage_edit.json","version":"1.0"},//修改基础数据
                "payment_manage_edit_financial_number":{"url":"../data/payment_manage_edit_financial_number.json","version":"1.0"},//修改PMO数据 修改基础数据
                "payment_state_pass":{"url":"../data/payment_state_pass.json","version":"1.0"},//通过支出
                "payment_state_submit":{"url":"../data/payment_state_submit.json","version":"1.0"},//提交支出
                "payment_state_cancel":{"url":"../data/payment_state_cancel.json","version":"1.0"},//作废支出
                "payment_state_del":{"url":"../data/payment_state_del.json","version":"1.0"},//删除支出
                "payment_state_recall":{"url":"../data/payment_state_recall.json","version":"1.0"},//撤回支出
                "payment_project_add":{"url":"../data/payment_project_add.json","version":"1.0"},//关联支出到项目
                "payment_project_list":{"url":"../data/payment_project_list.json","version":"1.0"},//查看所有支出和其所属项目
                "payment_project_list_pass":{"url":"../data/payment_project_list_pass.json","version":"1.0"},//查看所有支出和其所属项目
               
                "payment_project_list_by_project_id":{"url":"../data/payment_project_list_by_project_id.json","version":"1.0"},//查看项目的支出
                "payment_project_add_by_price":{"url":"../data/payment_project_add_by_price.json","version":"1.0"},//查看项目的支出
                "payment_project_edit":{"url":"../data/payment_project_edit.json","version":"1.0"},//查看项目的支出
                //视图
                // "addProject":{"url":"../json/addProject.json","version":"1.0"},//新建项目
                "addProjectGather":{"url":"../json/addProjectGather.json","version":"1.0"},//新建项目集
                "addTeacher":{"url":"../json/addTeacher.json","version":"1.0"},//新建讲师
                "addProjectAddress":{"url":"../json/addProjectAddress.json","version":"1.0"},//新增培训地点
                "budgetManage":{"url":"../json/budgetManage.json","version":"1.0"},//预算
                "editProject":{"url":"../json/editProject.json","version":"1.0"},//编辑项目
                "hotelTravelAddFrom":{"url":"../json/hotelTravelAddFrom.json","version":"1.0"},
                "hotelTravelSelectFrom":{"url":"../json/hotelTravelSelectFrom.json","version":"1.0"},
                "implementArrage":{"url":"../json/implementArrage.json","version":"1.0"},//实施安排
                "implementAddFrom":{"url":"../json/implementAddFrom.json","version":"1.0"},//实施安排修改，新增视图
                "implementSelectFrom":{"url":"../json/implementSelectFrom.json","version":"1.0"},//实施安排查看视图
                "longTravelAddFrom":{"url":"../json/longTravelAddFrom.json","version":"1.0"},
                "longTravelSelectFrom":{"url":"../json/longTravelSelectFrom.json","version":"1.0"},
                "mealTravelAddFrom":{"url":"../json/mealTravelAddFrom.json","version":"1.0"},
                "mealTravelSelectFrom":{"url":"../json/mealTravelSelectFrom.json","version":"1.0"},
                "newCard":{"url":"../json/newCard.json","version":"1.0"},
                "newFormlist":{"url":"../json/newFormlist.json","version":"1.0"},
                "newGroup":{"url":"../json/newGroup.json","version":"1.0"},
                "newFormlistGroup":{"url":"../json/newFormlistGroup.json","version":"1.0"},
                "projectViewCard":{"url":"../json/projectViewCard.json","version":"1.0"},//项目列表中的card
                "projectCard":{"url":"../json/projectCard.json","version":"1.0"},//项目列表中的card
                "projectTemplet":{"url":"../json/projectTemplet.json","version":"1.0"},//新建项目模板
                "projectCardHead":{"url":"../json/projectCardHead.json","version":"1.0"},
                "projectCardPage1":{"url":"../json/projectCardPage1.json","version":"1.0"},
                "projectCardPage2":{"url":"../json/projectCardPage2.json","version":"1.0"},
                "projectCardPage3":{"url":"../json/projectCardPage3.json","version":"1.0"},
                "projectCardFoot":{"url":"../json/projectCardFoot.json","version":"1.0"},
                "shortTravelAddFrom":{"url":"../json/shortTravelAddFrom.json","version":"1.0"},
                "shortTravelSelectFrom":{"url":"../json/shortTravelSelectFrom.json","version":"1.0"},
                "teacherCardGroup":{"url":"../json/teacherCardGroup.json","version":"1.0"},//讲师安排
                "teacherAddForm":{"url":"../json/teacherAddForm.json","version":"1.0"},//讲师安排修改，新增视图
                "teacherSelectFrom":{"url":"../json/teacherSelectFrom.json","version":"1.0"},//讲师安排查看视图
                "teacherDuty":{"url":"../json/teacherDuty.json","version":"1.0"},//讲师职责
                "travelExpensesGroup":{"url":"../json/travelExpensesGroup.json","version":"1.0"},//差旅安排
                "venueAddFrom":{"url":"../json/venueAddFrom.json","version":"1.0"},//会议室修改，新增视图
                "venueSelectFrom":{"url":"../json/venueSelectFrom.json","version":"1.0"}//会议室查看视图
            };
             
             
module.exports = local;